#!/bin/bash

ARGS="--param ../Labs/rmi-2223/C1-config.xml"
ARGS+=" --lab ../Labs/rmi-2223/C1-lab.xml"
ARGS+=" --grid ../Labs/rmi-2223/C1-grid.xml"
ARGS+=" --scoring 4"
(cd simulator; ./simulator $ARGS) &

sleep 1

(cd Viewer; ./Viewer --autoconnect)

killall simulator

echo Bye
