#!/bin/bash

ARGS="--param ../Labs/rmi-2223/C2a-config.xml"
ARGS+=" --lab ../Labs/rmi-2223/C2a-lab.xml"
ARGS+=" --grid ../Labs/rmi-2223/C2a-grid.xml"
ARGS+=" --scoring 5"
(cd simulator; ./simulator $ARGS) &

sleep 2

(cd Viewer; ./Viewer --autoconnect)

killall simulator

echo Bye
